cluster: "sbatch --parsable -p med2 --time={resources.runtime} --mem={resources.mem_mb} --job-name={rule}.{wildcards} -o snake_logs/{rule}.{wildcards}.%j.out -e snake_logs/{rule}.{wildcards}.%j.err --cpus-per-task {threads}"

use-conda: true
jobs: 256
default-resources: [mem_mb=10000, runtime=1440]
keep-going: true
rerun-incomplete: true
latency-wait: 60
#restart-times: 2
cluster-cancel: scancel
